# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_1', models.CharField(max_length=10)),
                ('pattern_2', models.CharField(max_length=10)),
                ('pattern_3', models.CharField(max_length=10)),
                ('pattern_4', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_1', models.CharField(max_length=10)),
                ('guess_2', models.CharField(max_length=10)),
                ('guess_3', models.CharField(max_length=10)),
                ('guess_4', models.CharField(max_length=10)),
                ('black', models.SmallIntegerField(default=0)),
                ('white', models.SmallIntegerField(default=0)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
