# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_1', models.CharField(max_length=10)),
                ('pattern_2', models.CharField(max_length=10)),
                ('pattern_3', models.CharField(max_length=10)),
                ('pattern_4', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=timezone.now())),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guess_1', models.CharField(max_length=10)),
                ('guess_2', models.CharField(max_length=10)),
                ('guess_3', models.CharField(max_length=10)),
                ('guess_4', models.CharField(max_length=10)),
                ('black', models.SmallIntegerField(default=0)),
                ('white', models.SmallIntegerField(default=0)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=timezone.now())),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
